"""Signal implementations for Pilot."""

from pilot_core.signals.error_cascade import (
    DEFAULT_ERROR_CASCADE_THRESHOLD,
    DEFAULT_ERROR_CASCADE_WINDOW,
    DEFAULT_MIN_OBSERVATIONS,
    ErrorCascadeResult,
    ErrorCascadeSignal,
    ToolOutcome,
    calibrate_error_cascade_score,
    evaluate_error_cascade,
    failure_rate,
    normalise_tool_outcome,
    recent_outcomes,
)

__all__ = [
    "DEFAULT_BASELINE_TURN_WINDOW",
    "DEFAULT_CONTEXT_SATURATION_THRESHOLD",
    "DEFAULT_ERROR_CASCADE_THRESHOLD",
    "DEFAULT_ERROR_CASCADE_WINDOW",
    "DEFAULT_MIN_BASELINE_TURNS",
    "DEFAULT_MIN_OBSERVATIONS",
    "DEFAULT_MIN_RECENT_TURNS",
    "DEFAULT_MIN_TOKEN_EVENTS",
    "DEFAULT_RECENT_TURN_WINDOW",
    "DEFAULT_TOKEN_BURN_RATIO_THRESHOLD",
    "MODEL_CONTEXT_LIMITS",
    "ContextSaturationResult",
    "ContextSaturationSignal",
    "ErrorCascadeResult",
    "ErrorCascadeSignal",
    "RawRecord",
    "SignalEngineV1Result",
    "SignalLikeResult",
    "TokenBurnResult",
    "TokenBurnSignal",
    "TokenEvent",
    "ToolOutcome",
    "TurnTokenUsage",
    "average_tokens_per_turn",
    "calibrate_context_saturation_score",
    "calibrate_error_cascade_score",
    "calibrate_token_burn_score",
    "context_saturation_ratio",
    "context_saturation_severity",
    "estimate_context_tokens",
    "evaluate_context_saturation",
    "evaluate_error_cascade",
    "evaluate_signal_engine_v1",
    "evaluate_token_burn",
    "failure_rate",
    "normalise_token_event",
    "normalise_tool_outcome",
    "normalise_turn_token_usage",
    "recent_and_baseline_windows",
    "recent_outcomes",
    "resolve_model_context_limit",
    "token_burn_ratio",
]

from pilot_core.signals.context_saturation import (
    DEFAULT_CONTEXT_SATURATION_THRESHOLD,
    DEFAULT_MIN_TOKEN_EVENTS,
    MODEL_CONTEXT_LIMITS,
    ContextSaturationResult,
    ContextSaturationSignal,
    TokenEvent,
    calibrate_context_saturation_score,
    context_saturation_ratio,
    context_saturation_severity,
    estimate_context_tokens,
    evaluate_context_saturation,
    normalise_token_event,
    resolve_model_context_limit,
)
from pilot_core.signals.token_burn import (
    DEFAULT_BASELINE_TURN_WINDOW,
    DEFAULT_MIN_BASELINE_TURNS,
    DEFAULT_MIN_RECENT_TURNS,
    DEFAULT_RECENT_TURN_WINDOW,
    DEFAULT_TOKEN_BURN_RATIO_THRESHOLD,
    TokenBurnResult,
    TokenBurnSignal,
    TurnTokenUsage,
    average_tokens_per_turn,
    calibrate_token_burn_score,
    evaluate_token_burn,
    normalise_turn_token_usage,
    recent_and_baseline_windows,
    token_burn_ratio,
)
from pilot_core.signals.v1 import (
    RawRecord,
    SignalEngineV1Result,
    SignalLikeResult,
    evaluate_signal_engine_v1,
)
